# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
