# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_land_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='location',
        ),
        migrations.AddField(
            model_name='land',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='land',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='land',
            name='subdistrict',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
