# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20171028_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maslocation',
            name='approve_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='maslocation',
            name='deposit_amount',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='maslocation',
            name='purchase_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='maslocation',
            name='sign_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
