# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20171028_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasLocation',
        ),
    ]
